---
title: Antonio Trento, theme Jeky New Age, the start Bootstrap themplate build for
  jekyll
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: A jekyll template for landing pages, portfolio and blogging
baseurl: ''
url: https://jekynewage.github.io
data-ad-slot: 2973388149
data-ad-client: ca-pub-9204963049240271
google_ad_client: ca-pub-9204963049240271
google_analytics: UA-86331249-1
addthis_id: ra-5644da281510c62f
disqus_account: jeky-new-age
social:
- title: twitter
  url: https://twitter.com/lantoniotrento
- title: facebook
  url: https://facebook.com/lantoniotrento
- title: google-plus
  url: https://plus.google.com/+AntoniotrentoIt
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
gems:
- jekyll-paginate
- jekyll-feed
